---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobjar-repo-deployment
  labels:
    app: flink-jobjar-repo
spec:
  selector:
    matchLabels:
      app: flink-jobjar-repo
  replicas: 1 
  template:
    metadata:
      labels:
        app: flink-jobjar-repo
    spec:
      containers:
      - name: flink-jobjar-repo
        image: idstudios/flink-jobjars:1.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobjar-service
spec:
  selector:
    app: flink-jobjar-repo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort      