version: "3.8"
services:

  sql-client:
    image: local/flink-stack:latest
    container_name: 'sql-client'
    command: 
      - /bin/sh
      - -c
      - |
        cp /host/jars/*.jar /opt/flink/lib/ 
        echo 'Copied /host/jars into /opt/flink/lib' 
        bin/sql-client.sh
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager     

    volumes:
      - ./host:/host

  jobmanager:
    container_name: 'jobmanager'
    image: local/flink-stack:latest
    ports:
      - "8081:8081"
      - "6123:6123"
    command: 
      - /bin/sh
      - -c
      - |
        mkdir -p /data/rocksdb/checkpoint
        mkdir -p /data/rocksdb/data
        mkdir -p /data/recovery
        cp /host/jars/*.jar /opt/flink/lib/ 
        echo 'Copied /host/jars into /opt/flink/lib' 
        /docker-entrypoint.sh jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: rocksdb
        state.backend.rocksdb.timer-service.factory: ROCKSDB
        state.checkpoints.dir: file:///data/rocksdb/checkpoint
        state.backend.rocksdb.localdir: file:///data/rocksdb/data
        state.backend.incremental: true
        high-availability.type: zookeeper
        high-availability.zookeeper.quorum: zk:2181
        high-availability.zookeeper.path.root: /flink
        high-availability.cluster-id: /cluster_one
        high-availability.storageDir: file:///data/recovery      
    volumes:
      - ./host:/host
      - ./data/:/data

  taskmanager:
    image: local/flink-stack:latest
    depends_on:
      - jobmanager
    command: 
      - /bin/sh
      - -c
      - |
        cp /host/jars/*.jar /opt/flink/lib/ 
        echo 'Copied /host/jars into /opt/flink/lib' 
        /docker-entrypoint.sh taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 100
        high-availability.type: zookeeper
        high-availability.zookeeper.quorum: zk:2181
        high-availability.zookeeper.path.root: /flink
        high-availability.cluster-id: /cluster_one
        high-availability.storageDir: file:///data/recovery      
    volumes:
      - ./host:/host
      - ./data/:/data

  zk:
    image: zookeeper:3.7.0
    restart: always
    container_name: zk
    hostname: zk
    ports:
      - "2181:2181"
      - "7001:7000"
    volumes:
      - zookeeper_log:/logs
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      placement:
        constraints: 
          - "node.role == manager"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk:2888:3888;2181 
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok


volumes:
  zookeeper_data:
  zookeeper_datalog:
  zookeeper_log:
