apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: enriched-orders-cluster
spec:
  image: idstudios/flink-enriched-orders:1.20
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "5"
  serviceAccount: flink
  podTemplate:
    spec:
      containers:
        # Do not change the main container name
        - name: flink-main-container
          env:
            - name: MYSQL_ERPDB_PWD
              valueFrom:
                secretKeyRef:
                  name: enriched-orders-mysql-erpdb-password
            - name: MYSQL_OPSDB_PWD
              valueFrom:
                secretKeyRef:
                  name: enriched-orders-mysql-opsdb-password
            - name: POSTGRES_SHIPDB_PWD
              valueFrom:
                secretKeyRef:
                  name: enriched-orders-postgres-shipdb-password
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///flink-jobjars/enriched-orders-job-1.0.0.jar
    parallelism: 2
    upgradeMode: stateless