apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: session-cluster
spec:
  image: idstudios/flink-enriched-orders:1.20
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "5"
  serviceAccount: flink
  podTemplate:
    spec:
      containers:
        # Do not change the main container name
        - name: flink-main-container
          # values in enriched-orders-jobs.properties can be overridden
          # as ENV variables, which will take precedence
          # K8s SECRETS can be used for sensitive data such as passwords
          env:
            - name: MYSQL_ERPDB_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: enriched-orders-mysql-erpdb-password
                  key: secret
            - name: MYSQL_OPSDB_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: enriched-orders-mysql-opsdb-password
                  key: secret
            - name: POSTGRES_SHIPDB_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: enriched-orders-postgres-shipdb-password
                  key: secret
            - name: AWS_REGION
              value: us-west-2
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: enriched-orders-aws-access-key-id
                  key: key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: enriched-orders-aws-secret-access-key
                  key: key
          volumeMounts:
            - mountPath: /flink-jobjars
              name: flink-jobjars  
      volumes:
        - name: flink-jobjars
          hostPath:
            path: /Users/seanhig/Workspace/flink-stack/examples/k8s/job-image
            type: DirectoryOrCreate                            
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1

