classloader.check-leaked-classloader: true     
jobmanager.rpc.address: jobmanager
rest.address: jobmanager

taskmanager.heap.size: 4096m
taskmanager.numberOfTaskSlots: 100

high-availability.type: zookeeper
high-availability.zookeeper.quorum: zk:2181
high-availability.zookeeper.path.root: /flink
high-availability.cluster-id: /cluster_one
high-availability.storageDir: file:///data/recovery    